QUERY = """
select sum(fe.qtd) QTD, fe.Faixa_Etaria, fe.SEXO
from (select count(e.ID_PESSOA) qtd,
         p.IC_SEXO SEXO, 
         CASE
              WHEN FLOOR(DATEDIFF(DAY, p.DT_NASCIMENTO , GETDATE()) / 365.25) BETWEEN 21 AND 23 THEN '21 a 23'
              WHEN FLOOR(DATEDIFF(DAY, p.DT_NASCIMENTO , GETDATE()) / 365.25) BETWEEN 24 AND 26 THEN '24 a 26'
              WHEN FLOOR(DATEDIFF(DAY, p.DT_NASCIMENTO , GETDATE()) / 365.25) BETWEEN 27 AND 29 THEN '27 a 29'
              WHEN FLOOR(DATEDIFF(DAY, p.DT_NASCIMENTO , GETDATE()) / 365.25) BETWEEN 30 AND 32 THEN '30 a 32'
              WHEN FLOOR(DATEDIFF(DAY, p.DT_NASCIMENTO , GETDATE()) / 365.25) BETWEEN 33 AND 35 THEN '33 a 35'
              WHEN FLOOR(DATEDIFF(DAY, p.DT_NASCIMENTO , GETDATE()) / 365.25) BETWEEN 36 AND 38 THEN '36 a 38'
              WHEN FLOOR(DATEDIFF(DAY, p.DT_NASCIMENTO , GETDATE()) / 365.25) BETWEEN 39 AND 41 THEN '39 a 41'
              WHEN FLOOR(DATEDIFF(DAY, p.DT_NASCIMENTO , GETDATE()) / 365.25) BETWEEN 42 AND 44 THEN '42 a 44'
              WHEN FLOOR(DATEDIFF(DAY, p.DT_NASCIMENTO , GETDATE()) / 365.25) BETWEEN 45 AND 47 THEN '45 a 47'
              WHEN FLOOR(DATEDIFF(DAY, p.DT_NASCIMENTO , GETDATE()) / 365.25) BETWEEN 48 AND 50 THEN '48 a 50'
              WHEN FLOOR(DATEDIFF(DAY, p.DT_NASCIMENTO , GETDATE()) / 365.25) BETWEEN 51 AND 53 THEN '51 a 53'
              WHEN FLOOR(DATEDIFF(DAY, p.DT_NASCIMENTO , GETDATE()) / 365.25) BETWEEN 54 AND 56 THEN '54 a 56'
              WHEN FLOOR(DATEDIFF(DAY, p.DT_NASCIMENTO , GETDATE()) / 365.25) BETWEEN 57 AND 59 THEN '57 a 59'
              WHEN FLOOR(DATEDIFF(DAY, p.DT_NASCIMENTO , GETDATE()) / 365.25) BETWEEN 60 AND 62 THEN '60 a 62'
              WHEN FLOOR(DATEDIFF(DAY, p.DT_NASCIMENTO , GETDATE()) / 365.25) >= 62 THEN 'Maior que 62'
              END AS Faixa_Etaria
         from  ENCERRAMENTO_PLANO_PARTIC e, PLANO_SITUACAO ps, pessoa p
         where 1=1
         and e.ID_SITUACAO = ps.ID_SITUACAO
         and e.ID_PESSOA = p.ID_PESSOA
         and concat(nr_ano_ref, FORMAT(NR_MES_REF, '00')) = ?
         and e.ID_SITUACAO  in (2,5,6,7,1,10)
         group by p.DT_NASCIMENTO, p.IC_SEXO) FE
group by fe.Faixa_Etaria, fe.SEXO
"""